POST http://localhost:3001/api/posts/project HTTP/1.1
content-type: application/json

{
    "userId": "urmom",
    "name": "competition bot",
    "description": "This bot was built for the Tower Takeover challenge. It took 3 months to design and build.",
    "image": "penis.png",
    "robots": [
        {
            "botName": "squarebot",
            "changeLog": "fixed chassis, began working on claw",
            "model": "amazon.com/mybot.obj",
            "botImage": "thumbnail.png",
            "partsCount": {"gears": 5, "hexnuts": 6, "locknuts": 7}
        },
        {
            "botName": "squarebot2",
            "changeLog": "fixed chassis, began working on claw",
            "model": "amazon.com/mybot.obj",
            "botImage": "thumbnail.png",
            "partsCount": {"gears": 5, "hexnuts": 6, "locknuts": 7}
        }
    ]
}

